import { ModelConfig } from "@shared/types";

export const MODELS: Record<string, ModelConfig> = {
  "claude-haiku-4-5": {
    id: "claude-haiku-4-5",
    publisher: "anthropic",
    modelId: "claude-haiku-4-5",
    displayName: "Claude 4.5 Haiku",
    maxInputTokens: 200000,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#10B981",
    description: "Fast and efficient with memory support",
    pricing: { input: 0.001, output: 0.005 },
    supportsMemory: true,
    endpointSupport: ["openrouter"],
  },
  "claude-sonnet-4-5": {
    id: "claude-sonnet-4-5",
    publisher: "anthropic",
    modelId: "claude-sonnet-4-5",
    displayName: "Claude 4.5 Sonnet",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#9333EA",
    description: "Latest Sonnet model with enhanced capabilities (supports 1M context + memory)",
    pricing: { input: 0.003, output: 0.015, inputPremium: 0.006, outputPremium: 0.0225 },
    supports1MContext: true,
    supportsMemory: true,
    endpointSupport: ["openrouter"],
  },
  "claude-opus-4-6": {
    id: "claude-opus-4-6",
    publisher: "anthropic",
    modelId: "claude-opus-4-6",
    displayName: "Claude 4.6 Opus",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "crown",
    color: "#B91C1C",
    description: "Latest flagship model with enhanced reasoning and memory",
    pricing: { input: 0.018, output: 0.085 },
    supportsMemory: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "none",
    endpointSupport: ["openrouter"],
  },
  "claude-sonnet-4-6": {
    id: "claude-sonnet-4-6",
    publisher: "anthropic",
    modelId: "claude-sonnet-4-6",
    displayName: "Claude 4.6 Sonnet",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#7C3AED",
    description: "Latest Sonnet with enhanced capabilities (supports 1M context + memory)",
    pricing: { input: 0.004, output: 0.018, inputPremium: 0.008, outputPremium: 0.028 },
    supports1MContext: true,
    supportsMemory: true,
    endpointSupport: ["openrouter"],
  },
  "grok-4-3": {
    id: "grok-4-3",
    publisher: "xai",
    modelId: "grok-4.3",
    displayName: "Grok 4.3",
    maxInputTokens: 2000000,
    maxOutputTokens: 32768,
    icon: "crown",
    color: "#FF6B00",
    description: "xAI's latest flagship — 2M context, native video understanding, document output, built-in reasoning",
    pricing: { input: 0.00125, output: 0.0025 },
    supportsSearch: true,
    supportsDeepThinking: false, // reasons automatically — reasoning_effort param not supported, returns error
    endpointSupport: ["xai"],
  },
  "grok-4-20-reasoning": {
    id: "grok-4-20-reasoning",
    publisher: "xai",
    modelId: "grok-4.20-0309-reasoning",
    displayName: "Grok 4.20 Reasoning (Beta)",
    maxInputTokens: 2000000,
    maxOutputTokens: 32768,
    icon: "crown",
    color: "#E91E63",
    description: "Grok 4.20 — reasons automatically before every response. Do not set reasoning effort (causes error).",
    pricing: { input: 0.002, output: 0.006 },
    supportsSearch: true,
    endpointSupport: ["xai"],
  },
  "grok-4-20-multi-agent": {
    id: "grok-4-20-multi-agent",
    publisher: "xai",
    modelId: "grok-4.20-multi-agent-0309",
    displayName: "Grok 4.20 Multi-Agent (Beta)",
    maxInputTokens: 2000000,
    maxOutputTokens: 32768,
    icon: "brain",
    color: "#9C27B0",
    description: "Grok 4.20 multi-agent — Fast/Balanced = 4 agents, Expert/Ultra = 16 agents. Best for deep research.",
    pricing: { input: 0.002, output: 0.006 },
    supportsDeepThinking: true,
    supportsSearch: true,
    endpointSupport: ["xai"],
  },
  "grok-4-20-non-reasoning": {
    id: "grok-4-20-non-reasoning",
    publisher: "xai",
    modelId: "grok-4.20-0309-non-reasoning",
    displayName: "Grok 4.20 Fast (Beta)",
    maxInputTokens: 2000000,
    maxOutputTokens: 32768,
    icon: "zap",
    color: "#FF9800",
    description: "Grok 4.20 beta low-latency variant, 2M context, no reasoning overhead",
    pricing: { input: 0.002, output: 0.006 },
    supportsSearch: true,
    endpointSupport: ["xai"],
  },
  "grok-4-1": {
    id: "grok-4-1",
    publisher: "xai",
    modelId: "grok-4-1",
    displayName: "Grok 4.1",
    maxInputTokens: 131072,
    maxOutputTokens: 16384,
    icon: "crown",
    color: "#E91E63",
    description: "xAI's latest flagship model with advanced reasoning and X search",
    pricing: { input: 0.005, output: 0.025 },
    supportsDeepThinking: true,
    supportsSearch: true,
    endpointSupport: ["xai"],
  },


  "grok-imagine": {
    id: "grok-imagine",
    publisher: "xai",
    modelId: "grok-imagine-image",
    displayName: "Grok Imagine (Standard)",
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    icon: "image",
    color: "#E91E63",
    description: "Generate and edit images — standard quality (being deprecated; use Quality model for new requests)",
    pricing: { input: 0, output: 0, perImage: 0.02 },
    supportsImageGeneration: true,
    endpointSupport: ["xai"],
  },
  "grok-imagine-quality": {
    id: "grok-imagine-quality",
    publisher: "xai",
    modelId: "grok-imagine-image-quality",
    displayName: "Grok Imagine Quality",
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    icon: "image",
    color: "#7C3AED",
    description: "Generate and edit images at higher fidelity — recommended quality model (~$0.05/image, varies by resolution)",
    pricing: { input: 0, output: 0, perImage: 0.05 },
    supportsImageGeneration: true,
    endpointSupport: ["xai"],
  },
  "grok-video": {
    id: "grok-video",
    publisher: "xai",
    modelId: "grok-video",
    displayName: "Grok Video",
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    icon: "video",
    color: "#1DA1F2",
    description: "Generate videos from text prompts",
    pricing: { input: 0.005, output: 0.025 },
    supportsVideoGeneration: true,
    endpointSupport: ["xai"],
  },
  "grok-voice": {
    id: "grok-voice",
    publisher: "xai",
    modelId: "grok-voice",
    displayName: "Grok Voice",
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    icon: "mic",
    color: "#17BF63",
    description: "Generate natural speech from text with multiple voice options",
    pricing: { input: 0.005, output: 0.025 },
    supportsTextToSpeech: true,
    endpointSupport: ["xai"],
  },
  "openrouter-auto": {
    id: "openrouter-auto",
    publisher: "openrouter",
    modelId: "openrouter/auto",
    displayName: "OpenRouter Auto",
    maxInputTokens: 200000,
    maxOutputTokens: 16384,
    icon: "target",
    color: "#6366F1",
    description: "Auto-selects best model for your prompt",
    pricing: { input: 0.002, output: 0.008 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-gpt-4o": {
    id: "openrouter-gpt-4o",
    publisher: "openrouter",
    modelId: "openai/gpt-4o",
    displayName: "GPT-4o (OR)",
    maxInputTokens: 128000,
    maxOutputTokens: 16384,
    icon: "brain",
    color: "#10A37F",
    description: "OpenAI GPT-4o via OpenRouter",
    pricing: { input: 0.0025, output: 0.01 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-llama-405b": {
    id: "openrouter-llama-405b",
    publisher: "openrouter",
    modelId: "meta-llama/llama-3.3-405b-instruct",
    displayName: "Llama 3.3 405B (OR)",
    maxInputTokens: 131072,
    maxOutputTokens: 16384,
    icon: "crown",
    color: "#0467DF",
    description: "Meta's largest open model via OpenRouter",
    pricing: { input: 0.002, output: 0.006 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-deepseek-r1": {
    id: "openrouter-deepseek-r1",
    publisher: "openrouter",
    modelId: "deepseek/deepseek-r1",
    displayName: "DeepSeek R1 (OR)",
    maxInputTokens: 65536,
    maxOutputTokens: 8192,
    icon: "brain",
    color: "#FF6B35",
    description: "DeepSeek reasoning model via OpenRouter",
    pricing: { input: 0.0014, output: 0.0056 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-5-flash": {
    id: "openrouter-gemini-3-5-flash",
    publisher: "openrouter",
    modelId: "google/gemini-3.5-flash",
    displayName: "Gemini 3.5 Flash (OR)",
    maxInputTokens: 1000000,
    maxOutputTokens: 65536,
    icon: "zap",
    color: "#4285F4",
    description: "Google's fast multimodal Gemini 3.5 Flash via OpenRouter (strong reasoning, coding, 1M context)",
    pricing: { input: 0.0015, output: 0.009 },
    supportsDeepThinking: true,
    supportsGrounding: true,
    endpointSupport: ["openrouter"],
  },
  "kilocode-claude": {
    id: "kilocode-claude",
    publisher: "kilocode",
    modelId: "anthropic/claude-sonnet-4",
    displayName: "Claude Sonnet (Kilo)",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#FF4081",
    description: "Claude Sonnet optimized for coding via Kilo Code",
    pricing: { input: 0.003, output: 0.015 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-claude-opus-4-6": {
    id: "kilocode-claude-opus-4-6",
    publisher: "kilocode",
    modelId: "anthropic/claude-opus-4-6",
    displayName: "Claude 4.6 Opus (Kilo)",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "crown",
    color: "#B91C1C",
    description: "Claude 4.6 Opus via Kilo Code",
    pricing: { input: 0.018, output: 0.085 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-claude-sonnet-4-6": {
    id: "kilocode-claude-sonnet-4-6",
    publisher: "kilocode",
    modelId: "anthropic/claude-sonnet-4-6",
    displayName: "Claude 4.6 Sonnet (Kilo)",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#7C3AED",
    description: "Claude 4.6 Sonnet via Kilo Code",
    pricing: { input: 0.004, output: 0.018 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-deepseek": {
    id: "kilocode-deepseek",
    publisher: "kilocode",
    modelId: "deepseek/deepseek-chat",
    displayName: "DeepSeek V3 (Kilo)",
    maxInputTokens: 65536,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#8BC34A",
    description: "DeepSeek V3 via Kilo Code - fast and efficient",
    pricing: { input: 0.00027, output: 0.0011 },
    endpointSupport: ["kilocode"],
  },
};

export const ENDPOINT_URLS = {
  openrouter: "https://openrouter.ai/api/v1",
  xai: "https://api.x.ai/v1",
  kilocode: "https://api.kilocode.ai/v1",
};
