import { ModelConfig } from "./types";

export const MODELS: Record<string, ModelConfig> = {
  "claude-haiku-4-5": {
    id: "claude-haiku-4-5",
    publisher: "anthropic",
    modelId: "claude-haiku-4-5@20251001:streamRawPredict",
    displayName: "Claude 4.5 Haiku",
    maxInputTokens: 200000,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#10B981",
    description: "Fast and efficient with memory support",
    pricing: { input: 0.001, output: 0.005 },
    supportsMemory: true,
    endpointSupport: ["vertex_ai"],
  },
  "claude-sonnet-4-5": {
    id: "claude-sonnet-4-5",
    publisher: "anthropic",
    modelId: "claude-sonnet-4-5@20250929:streamRawPredict",
    displayName: "Claude 4.5 Sonnet",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#9333EA",
    description: "Latest Sonnet model with enhanced capabilities (supports 1M context + memory)",
    pricing: { input: 0.003, output: 0.015, inputPremium: 0.006, outputPremium: 0.0225 },
    supports1MContext: true,
    supportsMemory: true,
    endpointSupport: ["vertex_ai"],
  },
  "claude-opus-4-5": {
    id: "claude-opus-4-5",
    publisher: "anthropic",
    modelId: "claude-opus-4-5@20251101:streamRawPredict",
    displayName: "Claude 4.5 Opus",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "crown",
    color: "#C92A2A",
    description: "Most capable model with memory for coding, agents, and enterprise workflows",
    pricing: { input: 0.015, output: 0.075 },
    supports1MContext: true,
    supportsMemory: true,
    endpointSupport: ["vertex_ai"],
  },
  "gemini-2-5-pro": {
    id: "gemini-2-5-pro",
    publisher: "google",
    modelId: "gemini-2.5-pro@default:streamGenerateContent",
    aiStudioModelId: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "target",
    color: "#4DABF7",
    description: "Advanced multimodal with 1M+ input / 65k output tokens",
    pricing: { input: 0.0025, output: 0.01 },
    supportsGrounding: true,
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-2-5-flash": {
    id: "gemini-2-5-flash",
    publisher: "google",
    modelId: "gemini-2.5-flash@default:streamGenerateContent",
    aiStudioModelId: "gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    maxInputTokens: 1048576,
    maxOutputTokens: 65535,
    icon: "zap",
    color: "#69DB7C",
    description: "Fastest response with 1M+ input / 65k output tokens",
    pricing: { input: 0.00025, output: 0.001 },
    supportsGrounding: true,
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-pro-preview": {
    id: "gemini-3-pro-preview",
    publisher: "google",
    modelId: "gemini-3-pro-preview:streamGenerateContent",
    aiStudioModelId: "gemini-3-pro-preview",
    displayName: "Gemini 3 Pro Preview",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#4285F4",
    description: "Next-gen multimodal model with 2M+ input / 65k output tokens",
    pricing: { input: 0.0025, output: 0.015 },
    supportsGrounding: true,
    defaultGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "none",
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-pro-deep-think": {
    id: "gemini-3-pro-deep-think",
    publisher: "google",
    modelId: "gemini-3-pro-preview:generateContent",
    aiStudioModelId: "gemini-3-pro-preview",
    displayName: "Gemini 3 Pro Deep Think",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "brain",
    color: "#9334E6",
    description: "Deep Thinking + Google Search Grounding",
    pricing: { input: 0.0025, output: 0.015 },
    supportsGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "high",
    endpointSupport: ["ai_studio"],
  },
  "gemini-3-flash-preview": {
    id: "gemini-3-flash-preview",
    publisher: "google",
    modelId: "gemini-3-flash-preview:streamGenerateContent",
    aiStudioModelId: "gemini-3-flash-preview",
    displayName: "Gemini 3 Flash Preview",
    maxInputTokens: 1048576,
    maxOutputTokens: 65535,
    icon: "zap",
    color: "#10B981",
    description: "Fast next-gen multimodal with 1M+ input tokens",
    pricing: { input: 0.0003, output: 0.0012 },
    supportsGrounding: true,
    defaultGrounding: true,
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "nano-banana-pro": {
    id: "nano-banana-pro",
    publisher: "google",
    modelId: "gemini-3-pro-image-preview:generateContent",
    aiStudioModelId: "gemini-3-pro-image-preview",
    displayName: "Nano Banana Pro",
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    icon: "image",
    color: "#FFD93D",
    description: "State-of-the-art image generation and editing",
    pricing: { input: 0.0025, output: 0.015 },
    supportsImageGeneration: true,
    endpointSupport: ["ai_studio"],
  },
  "gemini-deep-research": {
    id: "gemini-deep-research",
    publisher: "google",
    modelId: "deep-research-pro-preview-12-2025:streamGenerateContent",
    aiStudioModelId: "deep-research-pro-preview-12-2025",
    displayName: "Gemini Deep Research",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "search",
    color: "#EA4335",
    description: "Deep web research agent with multi-step reasoning and source synthesis",
    pricing: { input: 0.0025, output: 0.01 },
    supportsGrounding: true,
    supportsDeepResearch: true,
    endpointSupport: ["ai_studio"],
  },
  "grok-4-1": {
    id: "grok-4-1",
    publisher: "xai",
    modelId: "grok-4-1",
    displayName: "Grok 4.1",
    maxInputTokens: 131072,
    maxOutputTokens: 16384,
    icon: "crown",
    color: "#E91E63",
    description: "xAI's latest flagship model with advanced reasoning",
    pricing: { input: 0.005, output: 0.025 },
    supportsDeepThinking: true,
    endpointSupport: ["xai"],
  },
  "grok-3": {
    id: "grok-3",
    publisher: "xai",
    modelId: "grok-3",
    displayName: "Grok 3",
    maxInputTokens: 131072,
    maxOutputTokens: 8192,
    icon: "rocket",
    color: "#1DA1F2",
    description: "xAI's most capable model with real-time knowledge",
    pricing: { input: 0.003, output: 0.015 },
    endpointSupport: ["xai"],
  },
  "grok-3-fast": {
    id: "grok-3-fast",
    publisher: "xai",
    modelId: "grok-3-fast",
    displayName: "Grok 3 Fast",
    maxInputTokens: 131072,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#17BF63",
    description: "Fast, efficient reasoning with real-time X data access",
    pricing: { input: 0.0005, output: 0.0025 },
    endpointSupport: ["xai"],
  },
  "grok-3-mini": {
    id: "grok-3-mini",
    publisher: "xai",
    modelId: "grok-3-mini",
    displayName: "Grok 3 Mini",
    maxInputTokens: 131072,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#794BC4",
    description: "Lightweight reasoning model with thinking capabilities",
    pricing: { input: 0.0003, output: 0.0005 },
    supportsDeepThinking: true,
    endpointSupport: ["xai"],
  },
  "openrouter-auto": {
    id: "openrouter-auto",
    publisher: "openrouter",
    modelId: "openrouter/auto",
    displayName: "OpenRouter Auto",
    maxInputTokens: 200000,
    maxOutputTokens: 16384,
    icon: "target",
    color: "#6366F1",
    description: "Auto-selects best model for your prompt",
    pricing: { input: 0.002, output: 0.008 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-claude-sonnet": {
    id: "openrouter-claude-sonnet",
    publisher: "openrouter",
    modelId: "anthropic/claude-sonnet-4",
    displayName: "Claude Sonnet (OR)",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#9333EA",
    description: "Claude Sonnet via OpenRouter",
    pricing: { input: 0.003, output: 0.015 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-gpt-4o": {
    id: "openrouter-gpt-4o",
    publisher: "openrouter",
    modelId: "openai/gpt-4o",
    displayName: "GPT-4o (OR)",
    maxInputTokens: 128000,
    maxOutputTokens: 16384,
    icon: "brain",
    color: "#10A37F",
    description: "OpenAI GPT-4o via OpenRouter",
    pricing: { input: 0.0025, output: 0.01 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-llama-405b": {
    id: "openrouter-llama-405b",
    publisher: "openrouter",
    modelId: "meta-llama/llama-3.3-405b-instruct",
    displayName: "Llama 3.3 405B (OR)",
    maxInputTokens: 131072,
    maxOutputTokens: 16384,
    icon: "crown",
    color: "#0467DF",
    description: "Meta's largest open model via OpenRouter",
    pricing: { input: 0.002, output: 0.006 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-deepseek-r1": {
    id: "openrouter-deepseek-r1",
    publisher: "openrouter",
    modelId: "deepseek/deepseek-r1",
    displayName: "DeepSeek R1 (OR)",
    maxInputTokens: 65536,
    maxOutputTokens: 8192,
    icon: "brain",
    color: "#FF6B35",
    description: "DeepSeek reasoning model via OpenRouter",
    pricing: { input: 0.0014, output: 0.0056 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-pro": {
    id: "openrouter-gemini-3-pro",
    publisher: "openrouter",
    modelId: "google/gemini-3-pro",
    displayName: "Gemini 3 Pro (OR)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#4285F4",
    description: "Google's next-gen multimodal via OpenRouter",
    pricing: { input: 0.0025, output: 0.015 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-flash": {
    id: "openrouter-gemini-3-flash",
    publisher: "openrouter",
    modelId: "google/gemini-3-flash",
    displayName: "Gemini 3 Flash (OR)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65535,
    icon: "zap",
    color: "#10B981",
    description: "Fast next-gen multimodal via OpenRouter",
    pricing: { input: 0.0003, output: 0.0012 },
    endpointSupport: ["openrouter"],
  },
  "openrouter-gemini-3-deep-think": {
    id: "openrouter-gemini-3-deep-think",
    publisher: "openrouter",
    modelId: "google/gemini-3-pro-thinking",
    displayName: "Gemini 3 Deep Think (OR)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "brain",
    color: "#9334E6",
    description: "Deep Thinking + reasoning via OpenRouter",
    pricing: { input: 0.0025, output: 0.015 },
    supportsDeepThinking: true,
    endpointSupport: ["openrouter"],
  },
  "kilocode-claude": {
    id: "kilocode-claude",
    publisher: "kilocode",
    modelId: "anthropic/claude-sonnet-4",
    displayName: "Claude Sonnet (Kilo)",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#FF4081",
    description: "Claude Sonnet optimized for coding via Kilo Code",
    pricing: { input: 0.003, output: 0.015 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini": {
    id: "kilocode-gemini",
    publisher: "kilocode",
    modelId: "google/gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro (Kilo)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "target",
    color: "#00BCD4",
    description: "Gemini Pro optimized for coding via Kilo Code",
    pricing: { input: 0.0025, output: 0.01 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-deepseek": {
    id: "kilocode-deepseek",
    publisher: "kilocode",
    modelId: "deepseek/deepseek-chat",
    displayName: "DeepSeek V3 (Kilo)",
    maxInputTokens: 65536,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#8BC34A",
    description: "DeepSeek V3 via Kilo Code - fast and efficient",
    pricing: { input: 0.00027, output: 0.0011 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-pro": {
    id: "kilocode-gemini-3-pro",
    publisher: "kilocode",
    modelId: "google/gemini-3-pro",
    displayName: "Gemini 3 Pro (Kilo)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#4285F4",
    description: "Gemini 3 Pro optimized for coding via Kilo Code",
    pricing: { input: 0.0025, output: 0.015 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-flash": {
    id: "kilocode-gemini-3-flash",
    publisher: "kilocode",
    modelId: "google/gemini-3-flash",
    displayName: "Gemini 3 Flash (Kilo)",
    maxInputTokens: 1048576,
    maxOutputTokens: 65535,
    icon: "zap",
    color: "#10B981",
    description: "Gemini 3 Flash optimized for coding via Kilo Code",
    pricing: { input: 0.0003, output: 0.0012 },
    endpointSupport: ["kilocode"],
  },
  "kilocode-gemini-3-deep-think": {
    id: "kilocode-gemini-3-deep-think",
    publisher: "kilocode",
    modelId: "google/gemini-3-pro-thinking",
    displayName: "Gemini 3 Deep Think (Kilo)",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "brain",
    color: "#9334E6",
    description: "Deep Thinking + reasoning via Kilo Code",
    pricing: { input: 0.0025, output: 0.015 },
    supportsDeepThinking: true,
    endpointSupport: ["kilocode"],
  },
};

export const ENDPOINT_URLS = {
  vertex_ai: "https://aiplatform.googleapis.com",
  ai_studio: "https://generativelanguage.googleapis.com",
  openrouter: "https://openrouter.ai/api/v1",
  xai: "https://api.x.ai/v1",
  kilocode: "https://api.kilocode.ai/v1",
};
