import { ModelConfig } from "./types";

export const MODELS: Record<string, ModelConfig> = {
  "claude-haiku-4-5": {
    id: "claude-haiku-4-5",
    publisher: "anthropic",
    modelId: "claude-haiku-4-5@20251001:streamRawPredict",
    displayName: "Claude 4.5 Haiku",
    maxInputTokens: 200000,
    maxOutputTokens: 8192,
    icon: "zap",
    color: "#10B981",
    description: "Fast and efficient with memory support",
    pricing: { input: 0.001, output: 0.005 },
    supportsMemory: true,
    endpointSupport: ["vertex_ai"],
  },
  "claude-sonnet-4-5": {
    id: "claude-sonnet-4-5",
    publisher: "anthropic",
    modelId: "claude-sonnet-4-5@20250929:streamRawPredict",
    displayName: "Claude 4.5 Sonnet",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "rocket",
    color: "#9333EA",
    description: "Latest Sonnet model with enhanced capabilities (supports 1M context + memory)",
    pricing: { input: 0.003, output: 0.015, inputPremium: 0.006, outputPremium: 0.0225 },
    supports1MContext: true,
    supportsMemory: true,
    endpointSupport: ["vertex_ai"],
  },
  "claude-opus-4-5": {
    id: "claude-opus-4-5",
    publisher: "anthropic",
    modelId: "claude-opus-4-5@20251101:streamRawPredict",
    displayName: "Claude 4.5 Opus",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    icon: "crown",
    color: "#C92A2A",
    description: "Most capable model with memory for coding, agents, and enterprise workflows",
    pricing: { input: 0.015, output: 0.075 },
    supports1MContext: true,
    supportsMemory: true,
    endpointSupport: ["vertex_ai"],
  },
  "gemini-2-5-pro": {
    id: "gemini-2-5-pro",
    publisher: "google",
    modelId: "gemini-2.5-pro@default:streamGenerateContent",
    aiStudioModelId: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "target",
    color: "#4DABF7",
    description: "Advanced multimodal with 1M+ input / 65k output tokens",
    pricing: { input: 0.0025, output: 0.01 },
    supportsGrounding: true,
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-2-5-flash": {
    id: "gemini-2-5-flash",
    publisher: "google",
    modelId: "gemini-2.5-flash@default:streamGenerateContent",
    aiStudioModelId: "gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    maxInputTokens: 1048576,
    maxOutputTokens: 65535,
    icon: "zap",
    color: "#69DB7C",
    description: "Fastest response with 1M+ input / 65k output tokens",
    pricing: { input: 0.00025, output: 0.001 },
    supportsGrounding: true,
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-pro-preview": {
    id: "gemini-3-pro-preview",
    publisher: "google",
    modelId: "gemini-3-pro-preview:streamGenerateContent",
    aiStudioModelId: "gemini-3-pro-preview",
    displayName: "Gemini 3 Pro Preview",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "star",
    color: "#4285F4",
    description: "Next-gen multimodal model with 2M+ input / 65k output tokens",
    pricing: { input: 0.0025, output: 0.015 },
    supportsGrounding: true,
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "gemini-3-pro-deep-think": {
    id: "gemini-3-pro-deep-think",
    publisher: "google",
    modelId: "gemini-3-pro-preview:generateContent",
    aiStudioModelId: "gemini-3-pro-preview",
    displayName: "Gemini 3 Pro Deep Think",
    maxInputTokens: 2097152,
    maxOutputTokens: 65536,
    icon: "brain",
    color: "#9334E6",
    description: "Deep Thinking + Google Search Grounding",
    pricing: { input: 0.0025, output: 0.015 },
    supportsGrounding: true,
    supportsDeepThinking: true,
    defaultThinkingLevel: "high",
    endpointSupport: ["ai_studio"],
  },
  "gemini-3-flash-preview": {
    id: "gemini-3-flash-preview",
    publisher: "google",
    modelId: "gemini-3-flash-preview:streamGenerateContent",
    aiStudioModelId: "gemini-3-flash-preview",
    displayName: "Gemini 3 Flash Preview",
    maxInputTokens: 1048576,
    maxOutputTokens: 65535,
    icon: "zap",
    color: "#10B981",
    description: "Fast next-gen multimodal with 1M+ input tokens",
    pricing: { input: 0.0003, output: 0.0012 },
    supportsGrounding: true,
    endpointSupport: ["vertex_ai", "ai_studio"],
  },
  "nano-banana-pro": {
    id: "nano-banana-pro",
    publisher: "google",
    modelId: "gemini-3-pro-image-preview:generateContent",
    aiStudioModelId: "gemini-3-pro-image-preview",
    displayName: "Nano Banana Pro",
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    icon: "image",
    color: "#FFD93D",
    description: "State-of-the-art image generation and editing",
    pricing: { input: 0.0025, output: 0.015 },
    supportsImageGeneration: true,
    endpointSupport: ["ai_studio"],
  },
  "gemini-deep-research": {
    id: "gemini-deep-research",
    publisher: "google",
    modelId: "gemini-2.5-pro-deep-research-preview:streamGenerateContent",
    aiStudioModelId: "gemini-2.5-pro-deep-research",
    displayName: "Gemini Deep Research",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    icon: "search",
    color: "#EA4335",
    description: "Deep web research agent with multi-step reasoning and source synthesis",
    pricing: { input: 0.0025, output: 0.01 },
    supportsGrounding: true,
    supportsDeepResearch: true,
    endpointSupport: ["ai_studio"],
  },
};

export const ENDPOINT_URLS = {
  vertex_ai: "https://aiplatform.googleapis.com",
  ai_studio: "https://generativelanguage.googleapis.com",
};
